name: Build Peer Ban Helper Bin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Fix Nix setting dir
        run: |
          mkdir -p ~/.config/nix
          
      - name: Setup Cachix
        uses: cachix/cachix-action@v17
        with:
          name: lialh4
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build package
        run: |
          nix build .#peer-ban-helper-bin
